
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APP", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APP {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmailBatch", targetNamespace = "http://service/", className = "service.SendEmailBatch")
    @ResponseWrapper(localName = "sendEmailBatchResponse", targetNamespace = "http://service/", className = "service.SendEmailBatchResponse")
    @Action(input = "http://service/APP/sendEmailBatchRequest", output = "http://service/APP/sendEmailBatchResponse")
    public boolean sendEmailBatch(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://service/", className = "service.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://service/", className = "service.SendEmailResponse")
    @Action(input = "http://service/APP/sendEmailRequest", output = "http://service/APP/sendEmailResponse")
    public boolean sendEmail(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testWebService", targetNamespace = "http://service/", className = "service.TestWebService")
    @ResponseWrapper(localName = "testWebServiceResponse", targetNamespace = "http://service/", className = "service.TestWebServiceResponse")
    @Action(input = "http://service/APP/testWebServiceRequest", output = "http://service/APP/testWebServiceResponse")
    public String testWebService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
